// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkingManagementAPI.Context;

#nullable disable

namespace ParkingManagementAPI.Migrations
{
    [DbContext(typeof(ParkingContext))]
    [Migration("20251126103906_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ParkingManagementAPI.Models.Database.ChargeRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("AdditionalCharge")
                        .HasColumnType("float");

                    b.Property<double>("ChargePerMinute")
                        .HasColumnType("float");

                    b.Property<int>("VehicleType")
                        .HasColumnType("int");

                    b.Property<string>("VehicleTypeDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ChargeRates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("268d279a-e47e-4c93-9eb3-0a13142cad03"),
                            AdditionalCharge = 1.0,
                            ChargePerMinute = 0.10000000000000001,
                            VehicleType = 1,
                            VehicleTypeDisplayName = "Small"
                        },
                        new
                        {
                            Id = new Guid("b698623a-39ac-43a9-9b50-031f1a8605cb"),
                            AdditionalCharge = 1.0,
                            ChargePerMinute = 0.20000000000000001,
                            VehicleType = 2,
                            VehicleTypeDisplayName = "Medium"
                        },
                        new
                        {
                            Id = new Guid("c2ca03a5-e2f8-4c78-bde5-4eaa218f06da"),
                            AdditionalCharge = 1.0,
                            ChargePerMinute = 0.40000000000000002,
                            VehicleType = 3,
                            VehicleTypeDisplayName = "Large"
                        });
                });

            modelBuilder.Entity("ParkingManagementAPI.Models.Database.ParkingSpot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ParkingSpotNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ParkingSpots");

                    b.HasData(
                        new
                        {
                            Id = new Guid("658f6909-fda6-4132-aefc-c66cf9d00ebe"),
                            ParkingSpotNumber = 1
                        },
                        new
                        {
                            Id = new Guid("8830eaf5-60bd-4715-9f3c-920379ba1d7c"),
                            ParkingSpotNumber = 2
                        },
                        new
                        {
                            Id = new Guid("495b53ed-2944-4e49-a2f2-087bfc8cb3c8"),
                            ParkingSpotNumber = 3
                        },
                        new
                        {
                            Id = new Guid("513c30f8-d92d-466b-ab88-1c1d5416f223"),
                            ParkingSpotNumber = 4
                        },
                        new
                        {
                            Id = new Guid("bfcde73a-c71f-46f5-a2ab-9c89b50c0136"),
                            ParkingSpotNumber = 5
                        });
                });

            modelBuilder.Entity("ParkingManagementAPI.Models.Database.ParkingSpotAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChargeRateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<double?>("FinalCharge")
                        .HasColumnType("float");

                    b.Property<Guid>("ParkingSpotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("VehicleRegistration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChargeRateId");

                    b.HasIndex("ParkingSpotId");

                    b.ToTable("ParkingSpotAllocations");
                });

            modelBuilder.Entity("ParkingManagementAPI.Models.Database.ParkingSpotAllocation", b =>
                {
                    b.HasOne("ParkingManagementAPI.Models.Database.ChargeRate", "ChargeRate")
                        .WithMany("ParkingSpotAllocations")
                        .HasForeignKey("ChargeRateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ParkingManagementAPI.Models.Database.ParkingSpot", "ParkingSpot")
                        .WithMany("ParkingSpotAllocations")
                        .HasForeignKey("ParkingSpotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChargeRate");

                    b.Navigation("ParkingSpot");
                });

            modelBuilder.Entity("ParkingManagementAPI.Models.Database.ChargeRate", b =>
                {
                    b.Navigation("ParkingSpotAllocations");
                });

            modelBuilder.Entity("ParkingManagementAPI.Models.Database.ParkingSpot", b =>
                {
                    b.Navigation("ParkingSpotAllocations");
                });
#pragma warning restore 612, 618
        }
    }
}
